fishbidding/config/routes.rb
Rails.application.routes.draw do
  resources :sale_posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #set sale_posts#index as homepage
  root 'sale_posts#index'
end

fishbidding/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

fishbidding/app/models/sale_post.rb
class SalePost < ApplicationRecord
end

fishbidding/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

fishbidding/app/controllers/sale_posts_controller.rb
class SalePostsController < ApplicationController
  before_action :set_sale_post, only: [:show, :edit, :update, :destroy]

  # GET /sale_posts
  # GET /sale_posts.json
  def index
    @sale_posts = SalePost.all
  end

  # GET /sale_posts/1
  # GET /sale_posts/1.json
  def show
  end

  # GET /sale_posts/new
  def new
    @sale_post = SalePost.new
  end

  # GET /sale_posts/1/edit
  def edit
  end

  # POST /sale_posts
  # POST /sale_posts.json
  def create
    @sale_post = SalePost.new(sale_post_params)

    respond_to do |format|
      if @sale_post.save
        format.html { redirect_to @sale_post, notice: 'Sale post was successfully created.' }
        format.json { render :show, status: :created, location: @sale_post }
      else
        format.html { render :new }
        format.json { render json: @sale_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sale_posts/1
  # PATCH/PUT /sale_posts/1.json
  def update
    respond_to do |format|
      if @sale_post.update(sale_post_params)
        format.html { redirect_to @sale_post, notice: 'Sale post was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale_post }
      else
        format.html { render :edit }
        format.json { render json: @sale_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sale_posts/1
  # DELETE /sale_posts/1.json
  def destroy
    @sale_post.destroy
    respond_to do |format|
      format.html { redirect_to sale_posts_url, notice: 'Sale post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale_post
      @sale_post = SalePost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_post_params
      params.require(:sale_post).permit(:name, :bid, :size, :diet, :description, :duration)
    end
end

fishbidding/app/helpers/application_helper.rb
module ApplicationHelper
end

fishbidding/app/helpers/sale_posts_helper.rb
module SalePostsHelper
end

fishbidding/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fishbidding</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

fishbidding/app/views/sale_posts/_form.html.erb
<%= form_for(sale_post) do |f| %>
  <% if sale_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sale_post.errors.count, "error") %> prohibited this sale_post from being saved:</h2>

      <ul>
      <% sale_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :bid %>
    <%= f.text_field :bid %>
  </div>

  <div class="field">
    <%= f.label :size %>
    <%= f.text_field :size %>
  </div>

  <div class="field">
    <%= f.label :diet %>
    <%= f.text_field :diet %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :duration %>
    <%= f.text_field :duration %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

fishbidding/app/views/sale_posts/edit.html.erb
<h1>Editing Sale Post</h1>

<%= render 'form', sale_post: @sale_post %>

<%= link_to 'Show', @sale_post %> |
<%= link_to 'Back', sale_posts_path %>

fishbidding/app/views/sale_posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sale Posts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Bid</th>
      <th>Size</th>
      <th>Diet</th>
      <th>Description</th>
      <th>Duration</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sale_posts.each do |sale_post| %>
      <tr>
        <td><%= sale_post.name %></td>
        <td><%= sale_post.bid %></td>
        <td><%= sale_post.size %></td>
        <td><%= sale_post.diet %></td>
        <td><%= sale_post.description %></td>
        <td><%= sale_post.duration %></td>
        <td><%= link_to 'Show', sale_post %></td>
        <td><%= link_to 'Edit', edit_sale_post_path(sale_post) %></td>
        <td><%= link_to 'Destroy', sale_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sale Post', new_sale_post_path %>

fishbidding/app/views/sale_posts/new.html.erb
<h1>New Sale Post</h1>

<%= render 'form', sale_post: @sale_post %>

<%= link_to 'Back', sale_posts_path %>

fishbidding/app/views/sale_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sale_post.name %>
</p>

<p>
  <strong>Bid:</strong>
  <%= @sale_post.bid %>
</p>

<p>
  <strong>Size:</strong>
  <%= @sale_post.size %>
</p>

<p>
  <strong>Diet:</strong>
  <%= @sale_post.diet %>
</p>

<p>
  <strong>Description:</strong>
  <%= @sale_post.description %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @sale_post.duration %>
</p>

<%= link_to 'Edit', edit_sale_post_path(@sale_post) %> |
<%= link_to 'Back', sale_posts_path %>